"""Offline atlas audit: private source tiles and every model polygon UV."""
from pathlib import Path
import struct
import random
import sys

ROOT=Path(__file__).resolve().parents[1]

def inspect(outfit):
    bank=(ROOT/f'workspace/jun-import/jun/Jun-TTT1-arcade-P{outfit}.tim').read_bytes()
    tiles=[];o=0
    while o+8<len(bank):
        magic,flags=struct.unpack_from('<II',bank,o);assert magic==16;o+=8
        size=struct.unpack_from('<I',bank,o)[0];o+=size
        size,x,y,w,h=struct.unpack_from('<I4H',bank,o)
        tile=dict(x=x,y=y,w=w,h=h,mode=flags&3,offset=o+12)
        if not any(all(t[k]==tile[k] for k in ('x','y','w','h','mode')) for t in tiles):tiles.append(tile)
        o+=size
    model=(ROOT/f'workspace/jun-import/jun/Jun-TTT1-arcade-P{outfit}.3dm').read_bytes()
    word=lambda a:struct.unpack_from('<I',model,a)[0]
    half=lambda a:struct.unpack_from('<H',model,a)[0]
    faces=[]
    for row in range(30):
        m=word(32+row*56)
        if not m:continue
        uv=m+word(m);src=uv+half(uv)
        for kind in range(4):
            count=model[src];src+=1
            for _ in range(count):
                mat=word(m+4+model[src]*4);src+=1
                mode=(mat>>23)&3;ppw=4>>mode;points=[]
                for j in range(4 if kind&1 else 3):
                    v=half(uv+2+model[src]*2);src+=1
                    points.append((((mat>>16)&15)*64+(v&255)//ppw,(v>>8)+((mat>>20)&1)*256))
                matches=[i for i,t in enumerate(tiles) if t['mode']==mode and all(
                    t['x']<=x<t['x']+t['w'] and t['y']<=y<t['y']+t['h'] for x,y in points)]
                if len(matches)!=1:raise ValueError(('UV tile coverage',outfit,row,hex(mat),points,matches))
                faces.append(matches[0])
    return tiles,faces


def pack(tiles):
    for attempt in range(1000):
        rng=random.Random(attempt)
        order=sorted(range(len(tiles)),key=lambda i:(-tiles[i]['h'],-tiles[i]['w']) if attempt==0 else
                     (-tiles[i]['w']*tiles[i]['h']*(.5+rng.random()),))
        free=[(0,0,64,224),(64,0,16,128)];placed={}
        for i in order:
            w,h=tiles[i]['w'],tiles[i]['h']
            candidates=[(min(rw-w,rh-h),max(rw-w,rh-h),x,y) for x,y,rw,rh in free if w<=rw and h<=rh]
            if not candidates:break
            _,_,x,y=min(candidates);placed[i]=(x,y)
            updated=[]
            for fx,fy,fw,fh in free:
                if x>=fx+fw or x+w<=fx or y>=fy+fh or y+h<=fy:updated.append((fx,fy,fw,fh));continue
                if x>fx:updated.append((fx,fy,x-fx,fh))
                if x+w<fx+fw:updated.append((x+w,fy,fx+fw-x-w,fh))
                if y>fy:updated.append((fx,fy,fw,y-fy))
                if y+h<fy+fh:updated.append((fx,y+h,fw,fy+fh-y-h))
            free=[r for j,r in enumerate(updated) if not any(k!=j and
                  s[0]<=r[0] and s[1]<=r[1] and s[0]+s[2]>=r[0]+r[2] and s[1]+s[3]>=r[1]+r[3]
                  and (s!=r or k<j) for k,s in enumerate(updated))]
        if len(placed)==len(tiles):return [dict(t,dx=placed[i][0],dy=placed[i][1]) for i,t in enumerate(tiles)]
    raise ValueError('Could not pack verified costume into native fighter/face-backup space')


def header():
    lines=['/* Generated by tools/plan_jun_texture_atlas.py --header; no game assets embedded. */',
           '#ifndef TEKKEN3_JUN_TEXTURE_LAYOUT_H','#define TEKKEN3_JUN_TEXTURE_LAYOUT_H',
           'typedef struct { unsigned x,y,w,h,mode,offset,dx,dy; } JunTextureTile;',
           'static const unsigned jun_texture_counts[3]={26,22,28};',
           'static const JunTextureTile jun_texture_tiles[3][28]={']
    for outfit in (1,2,3):
        tiles,faces=inspect(outfit);tiles=pack(tiles)
        lines.append('    {')
        for t in tiles:lines.append('        {'+','.join(str(t[k]) for k in ('x','y','w','h','mode','offset','dx','dy'))+'},')
        lines.append('    },')
    lines+=['};',
            'static const JunTextureTile *jun_texture_tile(unsigned outfit,unsigned mode,unsigned x,unsigned y) {',
            '    if(outfit>=3)return 0;',
            '    for(unsigned i=0;i<jun_texture_counts[outfit];i++) {',
            '        const JunTextureTile *t=&jun_texture_tiles[outfit][i];',
            '        if(t->mode==mode && x>=t->x && x<t->x+t->w && y>=t->y && y<t->y+t->h)return t;',
            '    }','    return 0;','}','#endif']
    return '\n'.join(lines)+'\n'


if __name__=='__main__':
    if '--header' in sys.argv:print(header(),end='')
    else:
        for outfit in (1,2,3):
            tiles,faces=inspect(outfit);packed=pack(tiles)
            print(outfit,len(tiles),'tiles',len(faces),'polygons, complete single-tile coverage; packed')
